// artifacts/naar-noor/src/components/layout/Header.tsx
import { useState } from 'react';

export default function Header() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const toggleMobileMenu = () => setMobileMenuOpen(!mobileMenuOpen);

  return (
    <header className="fixed top-0 w-full z-50 border-b border-white/5 bg-[#0a0a0a]/80 backdrop-blur-md transition-all duration-300">
      <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
        <a href="#" className="flex items-center gap-3 group">
          <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-[#C65A1E] to-[#8B4513] flex items-center justify-center">
            <span className="font-forum text-xl font-bold text-white">2N</span>
          </div>
          <span className="font-forum text-xl text-white tracking-tight group-hover:text-[#C65A1E] transition-colors duration-300">
            Naar & Noor
          </span>
        </a>

        <nav className="hidden md:flex items-center gap-8">
          <a href="#about" className="text-sm text-neutral-300 hover:text-white transition-colors duration-200">About</a>
          <a href="#menu" className="text-sm text-neutral-300 hover:text-white transition-colors duration-200">Menu</a>
          <a href="#chefs" className="text-sm text-neutral-300 hover:text-white transition-colors duration-200">Chefs</a>
          <a href="#blog" className="text-sm text-neutral-300 hover:text-white transition-colors duration-200">Blog</a>
          <a href="#locations" className="text-sm text-neutral-300 hover:text-white transition-colors duration-200">Locations</a>
        </nav>

        <div className="flex items-center gap-4">
          <a
            href="#reserve"
            className="hidden md:inline-flex items-center justify-center px-5 py-2.5 text-sm font-medium text-white bg-[#C65A1E] rounded-xl hover:bg-[#a84915] hover:shadow-[0_0_20px_rgba(198,90,30,0.4)] transition-all duration-300"
          >
            Book a Table
          </a>
          <button
            onClick={toggleMobileMenu}
            className="md:hidden text-white p-2 hover:text-[#C65A1E] transition-colors"
          >
            <iconify-icon
              icon={mobileMenuOpen ? 'solar:close-circle-linear' : 'solar:hamburger-menu-linear'}
              width="28"
              height="28"
            ></iconify-icon>
          </button>
        </div>
      </div>

      {mobileMenuOpen && (
        <div className="md:hidden absolute top-20 left-0 w-full bg-[#0a0a0a]/95 backdrop-blur-lg border-b border-white/5 animate-fadeIn">
          <nav className="flex flex-col px-6 py-4 space-y-4">
            <a href="#about" onClick={toggleMobileMenu} className="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">About</a>
            <a href="#menu" onClick={toggleMobileMenu} className="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">Menu</a>
            <a href="#chefs" onClick={toggleMobileMenu} className="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">Chefs</a>
            <a href="#blog" onClick={toggleMobileMenu} className="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">Blog</a>
            <a href="#locations" onClick={toggleMobileMenu} className="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">Locations</a>
            <a
              href="#reserve"
              onClick={toggleMobileMenu}
              className="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-white bg-[#C65A1E] rounded-xl hover:bg-[#a84915] transition-all duration-300 mt-2"
            >
              Book a Table
            </a>
          </nav>
        </div>
      )}
    </header>
  );
}

// naar-noor/src/app/components/header/header.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { CartService } from '../../services/cart.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  mobileMenuOpen = false;
  readonly cart = inject(CartService);
  readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  toggleMobileMenu() {
    this.mobileMenuOpen = !this.mobileMenuOpen;
  }

  logout() {
    this.auth.logout();
    this.router.navigate(['/login']);
  }
}

<header data-cy="header" class="fixed top-0 w-full z-50 border-b border-white/5 bg-[#0a0a0a]/80 backdrop-blur-md transition-all duration-300">
  <div class="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
    <a routerLink="/" data-cy="logo" class="flex items-center gap-3 group">
      <div class="w-10 h-10 rounded-lg bg-gradient-to-br from-[#C65A1E] to-[#8B4513] flex items-center justify-center">
        <span class="font-['Forum'] text-xl font-bold text-white">2N</span>
      </div>
      <span class="font-['Forum'] text-xl text-white tracking-tight group-hover:text-[#C65A1E] transition-colors duration-300">
        Naar & Noor
      </span>
    </a>

    <nav data-cy="nav-menu" class="hidden md:flex items-center gap-8">
      <a routerLink="/" class="text-sm text-neutral-300 hover:text-white transition-colors duration-200">Home</a>
      <a routerLink="/about" class="text-sm text-neutral-300 hover:text-white transition-colors duration-200">About</a>
      <a routerLink="/menu" class="text-sm text-neutral-300 hover:text-white transition-colors duration-200">Menu</a>
      <a routerLink="/reservations" class="text-sm text-neutral-300 hover:text-white transition-colors duration-200">Reservations</a>
      <a routerLink="/contact" class="text-sm text-neutral-300 hover:text-white transition-colors duration-200">Contact</a>
    </nav>

    <div class="flex items-center gap-3">
      <!-- Cart button -->
      <button (click)="cart.toggle()"
              data-cy="cart-icon"
              class="relative flex items-center justify-center w-10 h-10 rounded-xl border border-white/10 text-neutral-300 hover:text-white hover:border-white/25 transition-all duration-200">
        <iconify-icon icon="solar:cart-large-2-linear" width="20"></iconify-icon>
        <span *ngIf="cart.count() > 0"
              data-cy="cart-badge"
              class="absolute -top-1.5 -right-1.5 min-w-[18px] h-[18px] flex items-center justify-center text-[10px] font-bold text-white bg-[#C65A1E] rounded-full px-1 shadow-[0_0_8px_rgba(198,90,30,0.5)]">
          {{ cart.count() > 9 ? '9+' : cart.count() }}
        </span>
      </button>

      <!-- Auth menu / Login -->
      <ng-container *ngIf="auth.isLoggedIn(); else loginBtn">
        <div data-cy="user-menu" class="flex items-center gap-3">
          <span class="hidden lg:inline text-xs text-neutral-400 font-sans font-light">
            {{ auth.userEmail() }}
          </span>
          <button (click)="logout()" class="text-sm text-neutral-300 hover:text-white transition-colors duration-200 border border-white/10 px-3 py-1.5 rounded-lg">
            Logout
          </button>
        </div>
      </ng-container>
      <ng-template #loginBtn>
        <a routerLink="/login" class="text-sm text-neutral-300 hover:text-white transition-colors duration-200 border border-white/10 px-3 py-1.5 rounded-lg">
          Login
        </a>
      </ng-template>

      <a routerLink="/reservations" class="hidden md:inline-flex items-center justify-center px-5 py-2.5 text-sm font-medium text-white bg-[#C65A1E] rounded-xl hover:bg-[#a84915] hover:shadow-[0_0_20px_rgba(198,90,30,0.4)] transition-all duration-300">
        Book a Table
      </a>
      <button (click)="toggleMobileMenu()" class="md:hidden text-white p-2 hover:text-[#C65A1E] transition-colors">
        <iconify-icon [icon]="mobileMenuOpen ? 'solar:close-circle-linear' : 'solar:hamburger-menu-linear'" width="28" height="28"></iconify-icon>
      </button>
    </div>
  </div>

  <!-- Mobile Menu -->
  <div
    *ngIf="mobileMenuOpen"
    class="md:hidden absolute top-20 left-0 w-full bg-[#0a0a0a]/95 backdrop-blur-lg border-b border-white/5 animate-fadeIn">
    <nav class="flex flex-col px-6 py-4 space-y-4">
      <a routerLink="/" (click)="toggleMobileMenu()" class="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">Home</a>
      <a routerLink="/about" (click)="toggleMobileMenu()" class="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">About</a>
      <a routerLink="/menu" (click)="toggleMobileMenu()" class="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">Menu</a>
      <a routerLink="/reservations" (click)="toggleMobileMenu()" class="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">Reservations</a>
      <a routerLink="/contact" (click)="toggleMobileMenu()" class="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">Contact</a>
      <ng-container *ngIf="auth.isLoggedIn(); else loginBtnMobile">
        <button (click)="logout(); toggleMobileMenu()" class="text-left text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">
          Logout
        </button>
      </ng-container>
      <ng-template #loginBtnMobile>
        <a routerLink="/login" (click)="toggleMobileMenu()" class="text-base text-neutral-200 hover:text-[#C65A1E] transition-colors duration-200 py-2">
          Login
        </a>
      </ng-template>
      <a routerLink="/reservations" (click)="toggleMobileMenu()" class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-white bg-[#C65A1E] rounded-xl hover:bg-[#a84915] transition-all duration-300 mt-2">
        Book a Table
      </a>
    </nav>
  </div>
</header>
